### ISSUE TITLE
Getter / Setter Support

### ISSUE THREAD

**Issue by jamieowen** [mattdesl/tweenr#2]
Hey,

Found a frustrating problem with tweenr in that it doesn't support tweening getter / setter properties.

The problem is down to the tween-objects module here :
https://github.com/mattdesl/tween-objects/blob/master/lib/end-target.js#L11

Basically using hasOwnProperty( 'x' ) on a getter / setter property evaluates to false... :(
Testing if it was undefined worked ok..

```
&& element[k] !== undefined
```

I can do a PR if need be?

**Comment by mattdesl** [comment]
Hey, this sounds like a bug. Can you post a small test case?

The following test passes in `tween-ticker`:

```js

test('operates on getters/setters', function(t) {
    var element = { value: [1, 0] }
    var x = 5
    Object.defineProperty(element, 'x', {
        get: function() {
            return x
        },
        set: function(val) {
            x = val
        }
    })

    var ticker = Ticker()
    var tween

    tween = ticker.to(element, { duration: 1, x: 10, delay: 1, value: [2, 4] })

    t.equal(element.x, 5, 'does not change until ticking')

    ticker.tick(1)
    t.equal(element.x, 5, 'delay is taken into account')

    ticker.tick(1)
    t.equal(element.x, 10, 'lerps arrays and getter/setter')

    t.end()
})
```

**Comment by jamieowen** [comment]
Man, this kind of bug makes me question what the hell I am doing still programming with javascript.. :)

With this one, the last lerps test fails for me.  ( I tried using your method with Object.defineProperties and that passes )
But this one on the prototype fails using defineProperties and defineProperty..
```
test('operates on getters/setters - alternative', function(t) {

    var Element = function() {
        this.__x = 0;
        this.value = [ 1, 0 ];
    };

    Object.defineProperties( Element.prototype, {
        x: {
            get: function(){
                return this.__x;
            },

            set: function( val ){
                this.__x = val;
            }
        }

    } );

    var element = new Element();
    element.x = 5;

    var ticker = Ticker()
    var tween = ticker.to(element, { duration: 1, x: 10, delay: 1, value: [2, 4] })

    t.equal(element.x, 5, 'does not change until ticking')

    ticker.tick(1)
    t.equal(element.x, 5, 'delay is taken into account')

    ticker.tick(1)
    t.equal(element.x, 10, 'lerps arrays and getter/setter')

    t.end()
})
```

**Comment by jamieowen** [comment]
Weirdly, If i comment out the line
```
&& element.hasOwnProperty(k)
```
In tape i get this error :
```
/Users/jamieowen/Sync/tween-ticker/node_modules/an-array/index.js:7
       arr.BYTES_PER_ELEMENT
          ^
TypeError: Cannot read property 'BYTES_PER_ELEMENT' of undefined
    at anArray (/Users/jamieowen/Sync/tween-ticker/node_modules/an-array/index.js:7:11)
    at getTargets (/Users/jamieowen/Sync/tween-ticker/node_modules/tween-objects/lib/end-target.js:23:22)
    at GroupTween.<anonymous> (/Users/jamieowen/Sync/tween-ticker/node_modules/tween-objects/lib/group.js:17:16)
    at Array.map (native)
    at GroupTween.ready (/Users/jamieowen/Sync/tween-ticker/node_modules/tween-objects/lib/group.js:16:28)
    at GroupTween.BaseTween.tick (/Users/jamieowen/Sync/tween-ticker/node_modules/tween-base/index.js:49:18)
    at TweenTicker.tick (/Users/jamieowen/Sync/tween-ticker/index.js:52:23)
    at Test.<anonymous> (/Users/jamieowen/Sync/tween-ticker/test.js:197:12)
    at Test.bound [as _cb] (/Users/jamieowen/Sync/tween-ticker/node_modules/tape/lib/test.js:62:32)
    at Test.run (/Users/jamieowen/Sync/tween-ticker/node_modules/tape/lib/test.js:75:10)
```

But if i replace with the following, the test passes.
```
&& element[k] !== undefined
```

**Comment by mattdesl** [comment]
After many moons I've finally come back to fixing this. Apologies!

https://github.com/mattdesl/tweenr/issues/3#issuecomment-178060561
